# Generated by Django 5.0 on 2023-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=64)),
                ('edition', models.IntegerField()),
                ('publisher', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=32)),
                ('publicationDate', models.DateField()),
                ('numberOfCopies', models.PositiveBigIntegerField()),
            ],
            options={
                'unique_together': {('title', 'author', 'edition', 'language', 'publisher')},
            },
        ),
    ]
